# Generated by Django 5.0.2 on 2024-04-05 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_person_id_user_alter_person_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 16, 16, 15, 77314)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 16, 16, 15, 77314)),
        ),
    ]
